In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
##sentences
sent = ['the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'I am a good boy',
        'I am a good developer',
        'understand the meaning of words',
        'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size = 10000

In [5]:
## One hot representation
one_hot_repr = [one_hot(words,voc_size) for words in sent]
one_hot_repr

[[7856, 9397, 2243, 5343],
 [7856, 9397, 2243, 8785],
 [7856, 7606, 2243, 6530],
 [1203, 6621, 14, 3858, 6969],
 [1203, 6621, 14, 3858, 2451],
 [5021, 7856, 7457, 2243, 6705],
 [8325, 6021, 5887, 3858]]

In [8]:
## word embedding representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np 

In [11]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr,padding = 'pre', maxlen = sent_length)
print(embedded_docs)

[[   0    0    0    0 7856 9397 2243 5343]
 [   0    0    0    0 7856 9397 2243 8785]
 [   0    0    0    0 7856 7606 2243 6530]
 [   0    0    0 1203 6621   14 3858 6969]
 [   0    0    0 1203 6621   14 3858 2451]
 [   0    0    0 5021 7856 7457 2243 6705]
 [   0    0    0    0 8325 6021 5887 3858]]


In [12]:
##feature representation
dim = 10 

In [14]:
model = Sequential()
model.add(Embedding(voc_size,dim,input_length= sent_length))
model.compile('adam','mse')

In [15]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [16]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 266ms/step


array([[[ 0.00680128, -0.03790414, -0.0243382 ,  0.03060495,
         -0.04398886,  0.04313817,  0.04488042, -0.04620863,
          0.00869088,  0.00736278],
        [ 0.00680128, -0.03790414, -0.0243382 ,  0.03060495,
         -0.04398886,  0.04313817,  0.04488042, -0.04620863,
          0.00869088,  0.00736278],
        [ 0.00680128, -0.03790414, -0.0243382 ,  0.03060495,
         -0.04398886,  0.04313817,  0.04488042, -0.04620863,
          0.00869088,  0.00736278],
        [ 0.00680128, -0.03790414, -0.0243382 ,  0.03060495,
         -0.04398886,  0.04313817,  0.04488042, -0.04620863,
          0.00869088,  0.00736278],
        [ 0.04938633,  0.03750488,  0.03076691,  0.02906059,
         -0.01457889, -0.02550662,  0.04431936,  0.04845477,
          0.02454996,  0.0359135 ],
        [-0.03670754,  0.01471957, -0.01581328,  0.04064503,
          0.0050782 , -0.02571541,  0.00097501, -0.01878996,
          0.01829857, -0.01627706],
        [ 0.02144608,  0.01137359,  0.04867697,  0.0

In [17]:
embedded_docs[0]

array([   0,    0,    0,    0, 7856, 9397, 2243, 5343])

In [18]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 53ms/step


array([[ 0.00680128, -0.03790414, -0.0243382 ,  0.03060495, -0.04398886,
         0.04313817,  0.04488042, -0.04620863,  0.00869088,  0.00736278],
       [ 0.00680128, -0.03790414, -0.0243382 ,  0.03060495, -0.04398886,
         0.04313817,  0.04488042, -0.04620863,  0.00869088,  0.00736278],
       [ 0.00680128, -0.03790414, -0.0243382 ,  0.03060495, -0.04398886,
         0.04313817,  0.04488042, -0.04620863,  0.00869088,  0.00736278],
       [ 0.00680128, -0.03790414, -0.0243382 ,  0.03060495, -0.04398886,
         0.04313817,  0.04488042, -0.04620863,  0.00869088,  0.00736278],
       [ 0.04938633,  0.03750488,  0.03076691,  0.02906059, -0.01457889,
        -0.02550662,  0.04431936,  0.04845477,  0.02454996,  0.0359135 ],
       [-0.03670754,  0.01471957, -0.01581328,  0.04064503,  0.0050782 ,
        -0.02571541,  0.00097501, -0.01878996,  0.01829857, -0.01627706],
       [ 0.02144608,  0.01137359,  0.04867697,  0.00894797,  0.04543977,
         0.00717336, -0.04781336,  0.02535057